import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from '@/components/Hero';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Hero title="Welcome back — Tailwind is installed" subtitle="This project now uses Tailwind utilities and dark mode support" ctaLabel="Open demo" />
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={100}
            height={20}
            priority
          />
          <div className={styles.intro}>
            <h1>To get started, edit the index.tsx file.</h1>
            <p>
              Looking for a starting point or more instructions? Head over to{" "}
              <a
                href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Templates
              </a>{" "}
              or the{" "}
              <a
                href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Learning
              </a>{" "}
              center.
            </p>
          </div>
          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={16}
                height={16}
              />
              Deploy Now
            </a>
            <a
              className={styles.secondary}
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Documentation
            </a>
          </div>
          {/* Tailwind demo: should pick up classes from tailwind */}
          <section className="mt-12 w-full flex justify-center">
            <div className="max-w-2xl p-8 bg-gradient-to-r from-indigo-50 via-white to-pink-50 rounded-2xl shadow-lg border border-gray-200">
              <h2 className="text-3xl font-extrabold text-indigo-700 mb-2">
                Tailwind is working ✅
              </h2>
              <p className="text-gray-700 mb-4">
                This paragraph uses Tailwind utility classes for spacing, color and typography. If you see a gradient background and the big bold heading, Tailwind is active.
              </p>
              <div className="flex gap-2">
                <button className="px-4 py-2 rounded-md bg-indigo-600 text-white hover:bg-indigo-700 transition">
                  Primary
                </button>
                <button className="px-4 py-2 rounded-md border border-indigo-600 text-indigo-600 hover:bg-indigo-50 transition">
                  Secondary
                </button>
              </div>
            </div>
          </section>
        </main>
      </div>
    </>
  );
}
